version: '3'

services:
###> doctrine/doctrine-bundle ###
  database:

###< doctrine/doctrine-bundle ###

volumes:
###> doctrine/doctrine-bundle ###
  database_data:
###< doctrine/doctrine-bundle ###
